services:
  - type: web
    name: crypto-tracker
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 3001
